permalink: /:title/
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-paginate
twitter:
  username: Jack_Franklin
paginate: 6
paginate_path: "/blog/page:num/"
include: ["_redirects"]
sass:
  sass_dir: _sass
  style: compressed
url: https://javascriptplayground.com
