permalink: /:title/
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-paginate
twitter:
  username: Jack_Franklin
include: ['_redirects']
sass:
  sass_dir: _sass
  style: compressed
url: https://javascriptplayground.com
defaults:
  - scope:
      path: ''
    values:
      image: /img/graph-image.png
